[package]
name = "rust-with-llms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
regex = "1.10.2"

[[bin]]
name = "aoc"
path = "src/aoc/main.rs"
